[ejs.landing]
updateAvailableTooltip = "Update Available"
usernamePlaceholder = "닉네임"
usernameEditButton = "Edit"
settingsTooltip = "온라인"
serverStatus = "서버"
serverStatusPlaceholder = "오프라인"
mojangStatus = "모장 서버 상태"
mojangStatusTooltipTitle = "서비스"
mojangStatusNETitle = "Non&nbsp;Essential"
newsButton = "뉴스"
launchButton = "플레이"
launchButtonPlaceholder = "&#8226; 서버를 선택하지 않았습니다."
launchDetails = "기다리세요.."
newsNavigationStatus = "{totalPages} 중 {currentPage}"
newsErrorLoadSpan = "뉴스 확인 중.."
newsErrorFailedSpan = "뉴스를 로드하지 못했습니다."
newsErrorRetryButton = "다시시도"
newsErrorNoneSpan = "뉴스 없음"

[ejs.login]
loginCancelText = "취소"
loginSubheader = "로그인"
loginEmailError = "* 잘못된 값"
loginEmailPlaceholder = "이메일 또는 닉네임"
loginPasswordError = "* 필수"
loginPasswordPlaceholder = "비밀번호"
loginForgotPasswordLink = "https://minecraft.net/password/forgot/"
loginForgotPasswordText = "비밀번호를 잊으셨나요?"
loginRememberMeText = "기억해줘?"
loginButtonText = "로그인"
loginNeedAccountLink = "https://minecraft.net/store/minecraft-java-edition/"
loginNeedAccountText = "가입하기"
loginPasswordDisclaimer1 = "귀하의 비밀번호는 Mojang으로 직접 전송되며 절대 저장되지 않습니다."
loginPasswordDisclaimer2 = "{appName}은 Mojang AB와 제휴되어 있지 않습니다."

[ejs.loginOptions]
loginOptionsTitle = "로그인"
loginWithMicrosoft = "마이크로소프트 로그인"
loginWithMojang = "모장 로그인"
cancelButton = "취소"

[ejs.overlay]
serverSelectHeader = "이용 가능한 서버"
serverSelectConfirm = "선택"
serverSelectCancel = "취소"
accountSelectHeader = "계정을 선택하세요"
accountSelectConfirm = "선택"
accountSelectCancel = "취소"

[ejs.settings]
navHeaderText = "설정"
navAccount = "계정"
navMinecraft = "마인크래프트"
navMods = "모드"
navJava = "자바"
navLauncher = "런처"
navAbout = "About"
navUpdates = "업데이트"
navDone = "확인"
tabAccountHeaderText = "계정 설정"
tabAccountHeaderDesc = "새 계정을 추가하거나 기존 계정을 관리하세요."
microsoftAccount = "마이크로소프트"
addMicrosoftAccount = "+ 마이크로소프트 계정 추가"
mojangAccount = "모장"
addMojangAccount = "+ 모장 계정 추가"
minecraftTabHeaderText = "마인크래프트 설정"
minecraftTabHeaderDesc = "게임 출시와 관련된 옵션"
gameResolutionTitle = "게임 해상도"
launchFullscreenTitle = "전체 화면으로 실행"
autoConnectTitle = "실행 시 서버에 자동으로 연결됩니다."
launchDetachedTitle = "런처에서 분리된 게임 프로세스를 실행합니다."
launchDetachedDesc = "게임이 분리되지 않은 경우 런처를 닫으면 게임도 닫힙니다."
tabModsHeaderText = "모드 설정"
tabModsHeaderDesc = "모드를 활성화하거나 비활성화합니다."
switchServerButton = "변경"
requiredMods = "Required Mods"
optionalMods = "Optional Mods"
dropinMods = "Drop-in Mods"
addMods = "모드 추가"
dropinRefreshNote = "(F5 to Refresh)"
shaderpacks = "쉐이터 팩"
shaderpackDesc = "셰이더를 활성화하거나 비활성화합니다. 셰이더는 강력한 설정에서만 원활하게 실행됩니다. 여기에 맞춤형 팩을 추가할 수 있습니다."
selectShaderpack = "Select Shaderpack"
tabJavaHeaderText = "자바 설정"
tabJavaHeaderDesc = "Manage the Java configuration (advanced)."
memoryTitle = "Memory"
maxRAM = "Maximum RAM"
minRAM = "Minimum RAM"
memoryDesc = "The recommended minimum RAM is 3 gigabytes. Setting the minimum and maximum values to the same value may reduce lag."
memoryTotalTitle = "Total"
memoryAvailableTitle = "Available"
javaExecutableTitle = "Java Executable"
javaExecSelDialogTitle = "Select Java Executable"
javaExecSelButtonText = "파일 닫기"
javaExecDesc = "The Java executable is validated before game launch."
javaPathDesc = "The path should end with <strong>{pathSuffix}</strong>."
jvmOptsTitle = "Additional JVM Options"
jvmOptsDesc = "Options to be provided to the JVM at runtime. <em>-Xms</em> and <em>-Xmx</em> should not be included."
launcherTabHeaderText = "Launcher Settings"
launcherTabHeaderDesc = "Options related to the launcher itself."
allowPrereleaseTitle = "Allow Pre-Release Updates."
allowPrereleaseDesc = "Pre-Releases include new features which may have not been fully tested or integrated.<br>This will always be true if you are using a pre-release version."
dataDirectoryTitle = "Data Directory"
selectDataDirectory = "Select Data Directory"
chooseFolder = "Choose Folder"
dataDirectoryDesc = "All game files and local Java installations will be stored in the data directory.<br>Screenshots and world saves are stored in the instance folder for the corresponding server configuration."
aboutTabHeaderText = "About"
aboutTabHeaderDesc = "View information and release notes for the current version."
aboutTitle = "{appName}"
stableRelease = "Stable Release"
versionText = "Version "
sourceGithub = "Source (GitHub)"
support = "고객센터"
devToolsConsole = "DevTools Console"
releaseNotes = "Release Notes"
changelog = "Changelog"
noReleaseNotes = "No Release Notes"
viewReleaseNotes = "View Release Notes on GitHub"
launcherUpdatesHeaderText = "Launcher Updates"
launcherUpdatesHeaderDesc = "Download, install, and review updates for the launcher."
checkForUpdates = "Check for Updates"
whatsNew = "What's New"
updateReleaseNotes = "Update Release Notes"

[ejs.waiting]
waitingText = "Waiting for Microsoft.."

[ejs.welcome]
continueButton = "CONTINUE"


[js.login]
login = "로그인"
loggingIn = "로그인"
success = "SUCCESS"
tryAgain = "Try Again"

[js.login.error]
invalidValue = "* Invalid Value"
requiredValue = "* Required"

[js.login.error.unknown]
title = "로그인 중 알 수 없는 오류"
desc = "알 수 없는 오류가 발생했습니다. 자세한 내용은 콘솔을 참조하세요."

[js.landing.launch]
pleaseWait = "Please wait.."
failureTitle = "실행 중 오류"
failureText = "자세한 내용은 콘솔(CTRL + Shift + i)을 참조하세요."
okay = "Okay"

[js.landing.selectedAccount]
noAccountSelected = "선택된 계정이 없습니다"

[js.landing.selectedServer]
noSelection = "서버를 선택하지 않았습니다."
loading = "로딩중.."

[js.landing.serverStatus]
server = "서버"
offline = "오프라인"
players = "플레이어"

[js.landing.systemScan]
checking = "Checking system info.."
noCompatibleJava = "No Compatible<br>Java Installation Found"
installJavaMessage = "In order to launch Minecraft, you need a 64-bit installation of Java {major}. Would you like us to install a copy?"
installJava = "자바 설치"
installJavaManually = "Install Manually"
javaDownloadPrepare = "Preparing Java Download.."
javaDownloadFailureTitle = "Error During Java Download"
javaDownloadFailureText = "See console (CTRL + Shift + i) for more details."
javaRequired = "Java is Required<br>to Launch"
javaRequiredMessage = 'A valid x64 installation of Java {major} is required to launch.<br><br>Please refer to our <a href="https://github.com/dscalzi/HeliosLauncher/wiki/Java-Management#manually-installing-a-valid-version-of-java">Java Management Guide</a> for instructions on how to manually install Java.'
javaRequiredDismiss = "I Understand"
javaRequiredCancel = "Go Back"

[js.landing.downloadJava]
findJdkFailure = "Failed to find OpenJDK distribution."
javaDownloadCorruptedError = "Downloaded JDK has a bad hash, the file may be corrupted."
extractingJava = "Extracting Java"
javaInstalled = "Java Installed!"

[js.landing.dlAsync]
loadingServerInfo = "Loading server information.."
fatalError = "Fatal Error"
unableToLoadDistributionIndex = "Could not load a copy of the distribution index. See the console (CTRL + Shift + i) for more details."
pleaseWait = "Please wait.."
errorDuringLaunchTitle = "Error During Launch"
seeConsoleForDetails = "See console (CTRL + Shift + i) for more details."
validatingFileIntegrity = "Validating file integrity.."
errorDuringFileVerificationTitle = "Error During File Verification"
downloadingFiles = "Downloading files.."
errorDuringFileDownloadTitle = "Error During File Download"
preparingToLaunch = "Preparing to launch.."
launchingGame = "Launching game.."
launchWrapperNotDownloaded = "The main file, LaunchWrapper, failed to download properly. As a result, the game cannot launch.<br><br>To fix this issue, temporarily turn off your antivirus software and launch the game again.<br><br>If you have time, please <a href=\"https://github.com/dscalzi/HeliosLauncher/issues\">submit an issue</a> and let us know what antivirus software you use. We'll contact them and try to straighten things out."
doneEnjoyServer = "Done. Enjoy the server!"
checkConsoleForDetails = "Please check the console (CTRL + Shift + i) for more details."

[js.landing.news]
checking = "Checking for News"

[js.settings.fileSelectors]
executables = "Executables"
allFiles = "All Files"

[js.settings.mstfLogin]
errorTitle = "문제가 발생했습니다."
errorMessage = "Microsoft 인증에 실패했습니다. 다시 시도해 주세요."
okButton = "승인"

[js.settings.mstfLogout]
errorTitle = "문제가 발생했습니다."
errorMessage = "Microsoft 로그아웃에 실패했습니다. 다시 시도해 주세요."
okButton = "승인"

[js.settings.authAccountSelect]
selectButton = "계정 선택"
selectedButton = "선택한 계정 &#10004;"

[js.settings.authAccountLogout]
lastAccountWarningTitle = "경고<br>이것이 마지막 계정입니다"
lastAccountWarningMessage = "런처를 사용하려면 하나 이상의 계정에 로그인해야 합니다. 이후에는 다시 로그인해야 합니다.<br><br>로그아웃하시겠습니까?"
confirmButton = "확실하십니까?"
cancelButton = "취소"

[js.settings.authAccountPopulate]
username = "닉네임"
uuid = "UUID"
selectAccount = "계정 선택"
selectedAccount = "선택한 계정 ✓"
logout = "로그아웃"

[js.settings.dropinMods]
removeButton = "삭제"
deleteFailedTitle = "<br>드롭인 모드 {fullName}을(를) 삭제하지 못했습니다."
deleteFailedMessage = "파일이 사용 중이 아닌지 확인하고 다시 시도하세요."
failedToggleTitle = "하나 이상의 드롭인 모드를<br>전환하지 못했습니다."
okButton = "Okay"

[js.settings.serverListing]
mainServer = "서버"

[js.settings.java]
selectedJava = "Selected: Java {version} ({vendor})"
invalidSelection = "Invalid Selection"
requiresJava = "Requires Java {major} x64."
availableOptions = "Available Options for Java {major} (HotSpot VM)"

[js.settings.about]
preReleaseTitle = "Pre-release"
stableReleaseTitle = "Stable Release"
releaseNotesFailed = "Failed to load release notes."

[js.settings.updates]
newReleaseTitle = "새로운 버전"
newPreReleaseTitle = "새로운 시험판 버전 가능"
downloadingButton = "다운로드중.."
downloadButton = 'GitHub에서 다운로드<span style="font-size: 10px;color: grey;text-shadow: none !important;">런처를 닫고 dmg를 실행하여 업데이트하세요.</span>'
latestVersionTitle = "최신 버전을 실행 중입니다."
checkForUpdatesButton = "업데이트 확인"
checkingForUpdatesButton = "업데이트 확인 중.."

[js.uibinder.startup]
fatalErrorTitle = "Fatal Error: Unable to Load Distribution Index"
fatalErrorMessage = "배포 색인을 다운로드하기 위해 서버에 연결을 설정할 수 없습니다. 로드할 수 있는 로컬 복사본이 없습니다. <br><br>배포지수는 최신 서버 정보를 제공하는 필수 파일입니다. 런처가 없으면 런처를 시작할 수 없습니다. 인터넷에 연결되어 있는지 확인하고 애플리케이션을 다시 실행하세요."
closeButton = "닫음"

[js.uibinder.validateAccount]
failedMessageTitle = "로그인을 새로 고치지 못했습니다."
failedMessage = "<strong>{account}</strong>에 대한 로그인을 새로 고칠 수 없습니다. 다른 계정을 선택하거나 다시 로그인하세요."
failedMessageSelectAnotherAccount = "<strong>{account}</strong>에 대한 로그인을 새로 고칠 수 없습니다. 다시 로그인해주세요."
loginButton = "로그인"
selectAnotherAccountButton = "다른 계정 선택"

[js.uicore.autoUpdate]
checkingForUpdateButton = "업데이트 확인 중..."
installNowButton = "지금 설치"
checkForUpdatesButton = "업데이트 확인"